# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import authentication_example_pb2 as authentication__example__pb2


class HelloServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHello = channel.unary_unary(
        '/pyconke.example.authetication.HelloService/SayHello',
        request_serializer=authentication__example__pb2.HelloRequest.SerializeToString,
        response_deserializer=authentication__example__pb2.HelloResponse.FromString,
        )


class HelloServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SayHello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HelloServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHello': grpc.unary_unary_rpc_method_handler(
          servicer.SayHello,
          request_deserializer=authentication__example__pb2.HelloRequest.FromString,
          response_serializer=authentication__example__pb2.HelloResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pyconke.example.authetication.HelloService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
